name: Build osgearth on Windows

on:
  push:
    branches:
      - main  # 可以设置为其他分支，如开发分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境构建

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 获取代码

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1  # 设置 Visual Studio 编译环境
      with:
        vs-version: 'latest'  # 使用最新版本的 Visual Studio

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'  # 安装 CMake
        choco install git  # 安装 Git
        choco install boost  # 安装 Boost 库
        choco install sqlite  # 安装 SQLite 库
        choco install proj  # 安装 PROJ 库
        choco install curl  # 安装 cURL 库

    - name: Build osgearth
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" ..
        msbuild osgearth.sln /p:Configuration=Release  # 使用 MSBuild 编译

    - name: Create release package
      run: |
        cd build
        Compress-Archive -Path * -DestinationPath osgearth_build.zip  # 将构建结果打包成 ZIP 文件

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: osgearth-build
        path: build/osgearth_build.zip  # 上传 ZIP 文件作为构建工件
