name: Build osgearth

on:
  push:
    branches:
      - main  # 你可以选择其他分支
  pull_request:
    branches:
      - main  # 在 PR 到 main 时触发构建

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为构建环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 获取代码

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ libproj-dev libsqlite3-dev libcurl4-openssl-dev libboost-all-dev

    - name: Build osgearth
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)  # 使用多核编译

    - name: Create release package
      run: |
        cd build
        tar -czf osgearth_build.tar.gz *  # 将编译结果打包为 tar.gz 文件

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: osgearth-build
        path: build/osgearth_build.tar.gz  # 上传 tar.gz 文件作为构建工件

